#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stiggio/stigg-go,github.com/stainless-sdks/stigg-go"

REPLACEMENT="${1:-"../stigg-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/stiggio/stigg-go="$REPLACEMENT"
go mod tidy -e
